FROM rabbitmq:3.8.5

RUN rabbitmq-plugins enable rabbitmq_management  #enabling a management portal

RUN rabbitmq-plugins enable rabbitmq_web_stomp

RUN apt-get update && apt-get install -y -qq \
 curl=7.58.0-2ubuntu3.9 \
 && apt-get -qq clean \
 && apt-get -qq autoremove \
 && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
