# ARM - if you use ARM uncomment the following line
# FROM docker.io/vprokopets/waffle_temp:latest

# AMD - if you use AMD uncomment the following line
FROM docker.io/vprokopets/waffle_temp_amd:latest