apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
spec:
  selector:
    matchLabels:
      app: front-end
  replicas: 1
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
        - name: front-end
          image: master-node:5000/local/front-end_image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: basic