/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VAppBarNavIcon: typeof import('vuetify/lib')['VAppBarNavIcon']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardActions: typeof import('vuetify/lib')['VCardActions']
    VCardItem: typeof import('vuetify/lib')['VCardItem']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VCheckbox: typeof import('vuetify/lib')['VCheckbox']
    VChip: typeof import('vuetify/lib')['VChip']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VDataTableVirtual: typeof import('vuetify/lib')['VDataTableVirtual']
    VDialog: typeof import('vuetify/lib')['VDialog']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VExpansionPanel: typeof import('vuetify/lib')['VExpansionPanel']
    VExpansionPanels: typeof import('vuetify/lib')['VExpansionPanels']
    VExpansionPanelText: typeof import('vuetify/lib')['VExpansionPanelText']
    VExpansionPanelTitle: typeof import('vuetify/lib')['VExpansionPanelTitle']
    VFileInput: typeof import('vuetify/lib')['VFileInput']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VList: typeof import('vuetify/lib')['VList']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VListItemSubtitle: typeof import('vuetify/lib')['VListItemSubtitle']
    VListItemTitle: typeof import('vuetify/lib')['VListItemTitle']
    VListSubheader: typeof import('vuetify/lib')['VListSubheader']
    VMain: typeof import('vuetify/lib')['VMain']
    VMenu: typeof import('vuetify/lib')['VMenu']
    VNavigationDrawer: typeof import('vuetify/lib')['VNavigationDrawer']
    VProgressLinear: typeof import('vuetify/lib')['VProgressLinear']
    VRow: typeof import('vuetify/lib')['VRow']
    VSnackbar: typeof import('vuetify/lib')['VSnackbar']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VTab: typeof import('vuetify/lib')['VTab']
    VTabs: typeof import('vuetify/lib')['VTabs']
    VTabsWindow: typeof import('vuetify/lib')['VTabsWindow']
    VTabsWindowItem: typeof import('vuetify/lib')['VTabsWindowItem']
    VTextField: typeof import('vuetify/lib')['VTextField']
  }
}
