
# Service
FROM python:3-alpine

RUN mkdir -p /usr/src/app 
WORKDIR /usr/src/app

COPY . /usr/src/app

# TODO: install from source code
RUN apk add --no-cache curl && \
 python3 -mpip install requests 
 
EXPOSE 8080
CMD [ "python", "-u", "./intro.py" ]