FROM ubuntu:18.04

# Updating the system and adding python3
RUN apt-get update && apt-get install -y -qq \
    software-properties-common=0.96.24.32.14 \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update && apt-get install -y -qq \
    apt-utils=1.6.12ubuntu0.1 \
    rsync=3.1.2-2.1ubuntu1.1 \
    vim=2:8.0.1453-1ubuntu1.4 \
    python3.7 \
    python3-pip \
    python3.7-dev \
    wget=1.19.4-1ubuntu2.2 \
    && apt-get -qq clean \
    && apt-get -qq autoremove \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Installing dockerize tool
ENV DOCKERIZE_VERSION v0.6.1

RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

# Installing project requirements
COPY requirements.txt /root
RUN python3.7 -m pip install --no-cache-dir -q -r /root/requirements.txt
