FROM --platform=linux/amd64 ubuntu:24.04

# Updating the system and adding python3
RUN apt-get update && apt-get install -y -qq \
    software-properties-common \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update && apt-get install -y -qq \
    apt-utils\
    rsync \
    vim \
    python3.12 \
    python3-pip \
    python3.12-dev \
    wget \
    && apt-get -qq clean \
    && apt-get -qq autoremove \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir -p /opt/conda && \
    mkdir -p /miniconda && \
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /miniconda/miniconda.sh && \
    bash /miniconda/miniconda.sh -b -u -p /opt/conda/ && \
    rm /miniconda/miniconda.sh

ENV PATH /opt/conda/bin:$PATH
RUN conda update conda -y

COPY environment.yml /root
RUN conda env create --file /root/environment.yml -y

# Installing dockerize tool
ENV DOCKERIZE_VERSION=v0.8.0

RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz
