name: brise-261

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pytest-cov
  - setuptools
  - scikit-learn[alldeps]=1.6.1
  - PyYAML
  - statsmodels
  - scipy
  - pytest
  - pika
  - pymongo
  - numexpr
  - pandas
  - pygmo
  - flake8
  - allpairspy
  - textx
  - selenium
  - webdriver-manager
