# RabbitMQ Configuration File
# Related doc guide: https://www.rabbitmq.com/configure.html
listeners.tcp.default = 49153
loopback_users.guest = false
heartbeat = 1000

# Logging
log.console = true
log.console.level = error
log.file.level = warning

# Management Plugin
# Related doc guide: https://www.rabbitmq.com/management.html
management.load_definitions = /etc/rabbitmq/definitions.json
management.tcp.port = 49154

# Web STOMP Plugin
# Related doc guide: https://www.rabbitmq.com/stomp.html
web_stomp.port = 49155

# MQTT Plugin
# Related doc guide: https://github.com/rabbitmq/rabbitmq-mqtt/blob/stable/README.md
mqtt.proxy_protocol = true

deprecated_features.permit.transient_nonexcl_queues = true