FROM python:3-alpine

RUN mkdir -p /usr/src/app 
WORKDIR /usr/src/app

RUN pip install --upgrade pip && \
pip install Flask && \
pip install -U socketIO-client

COPY . /usr/src/app

EXPOSE 8080
CMD [ "python", "-u", "./w_intro.py" ]