FROM --platform=linux/amd64 ubuntu:24.04
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Updating the system
RUN apt-get update && apt-get install -y -qq \
    wget \
    rsync \
    vim \
    git \
    unzip \
    python3.12 \
    python3-pip \
    python3.12-dev \
# Installing Java (Open JDK) for Rapidminer and MQUAT problems
    && apt-get -y -qq install --no-install-recommends openjdk-8-jdk\
# Installing R and related packages for Rapidminer
    && apt-get install -y -qq r-base && \
    Rscript -e "install.packages('data.table', repos='http://cran.rstudio.com/')" && \
    Rscript -e "install.packages('ROCR', repos='http://cran.rstudio.com/')" && \
    Rscript -e "install.packages('PRROC', repos='http://cran.rstudio.com/')" \
    && apt-get -qq clean \
    && apt-get -qq autoremove \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
ENV JAVA_HOME="$(dirname $(dirname $(readlink -f $(which javac))))"

RUN mkdir -p /opt/conda && \
    mkdir -p /miniconda && \
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /miniconda/miniconda.sh && \
    bash /miniconda/miniconda.sh -b -u -p /opt/conda/ && \
    rm /miniconda/miniconda.sh

ENV PATH=/opt/conda/bin:$PATH
COPY environment.yml /root
RUN conda env create --file /root/environment.yml -y
RUN conda update conda -y

# Installing dockerize tool
ENV DOCKERIZE_VERSION=v0.8.0

RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz