FROM python:3-alpine

RUN mkdir -p /usr/src/app 
WORKDIR /usr/src/app

RUN pip install --upgrade pip && \
pip install -U python-socketio && \
pip install -U "python-engineio[client]"

COPY . /usr/src/app

EXPOSE 8080
CMD [ "python", "-u", "./w_intro.py" ]