
# Service
FROM python:3-alpine

RUN mkdir -p /usr/src/app 
WORKDIR /usr/src/app

COPY . /usr/src/app

RUN apk add --no-cache curl && \
 python3 -mpip install requests && \
 pip install Flask && \
 pip install flask-cors
 
EXPOSE 80
CMD [ "python", "-u", "./intro.py" ]