
# Service
FROM python:3-alpine

RUN mkdir -p /usr/src/app 
WORKDIR /usr/src/app

COPY . /usr/src/app

RUN apk add --no-cache curl build-base && \
 pip install --upgrade pip && \
 pip install Flask && \
 pip install flask-cors && \
 pip install flask-socketio && \
 pip install eventlet
 
EXPOSE 49153
CMD [ "python", "-u", "./intro.py" ]
# CMD [ "sh" ]