name: Code Coverage Badge

on:
  push:
    branches: [develop]

permissions:
  contents: write

jobs:
  if_merged:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: true

      - name: Extract coverage %
        shell: bash -l {0}
        run: |
          PERCENT=$(( RANDOM % 101 ))
          echo "coverage=${PERCENT}"
          mkdir -p badge-data

          # Choose color based on percentage
          # 90-100% brightgreen
          # 80-89% green
          # 70-79% yellowgreen
          # 60-69% yellow
          # 50-59%  orange
          # <50% red
          if (( PERCENT >= 90 )); then
              COLOR=brightgreen
          elif (( PERCENT >= 80 )); then
              COLOR=green
          elif (( PERCENT >= 70 )); then
              COLOR=yellowgreen
          elif (( PERCENT >= 60 )); then
              COLOR=yellow
          elif (( PERCENT >= 50 )); then
              COLOR=orange
          else
              COLOR=red
          fi

          # create url with percentage
          n=$(($PERCENT+0))
          url="https://img.shields.io/badge/Code%20Coverage-${PERCENT}%25-${COLOR}?style=flat"
          curl -sSL --fail "$url" -o badge-data/coverage.svg
      # Commit updated badge svg
      - name: Commit badge data
        uses: stefanzweifel/git-auto-commit-action@v4

        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Update coverage badge"
          file_pattern: badge-data/coverage.svg
          branch: main